spring.application.name=pr-test

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/prtest}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:prtest}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:prtest}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
